# Assumes that generated files are single-file, i.e.
# in the csproj file, <PublishSingleFile>true</PublishSingleFile> is set.

name: Publish SRTimestampFixer

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  PROJECT_NAME: SRTimestampFixer
  PROJECT_ROOT: ./SRTimestampFixer
  DOTNET_VERSION: '8.0.x'

jobs:

  build:
    strategy:
      matrix:
        include:
          # See https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#known-rids
          - os: windows-latest
            build_target: win-x64
            artifact_extension: .exe
          - os: macos-latest
            build_target: osx-x64
            artifact_extension: ''
          - os: macos-latest
            build_target: osx-arm64
            artifact_extension: ''
          - os: ubuntu-latest
            build_target: linux-x64
            artifact_extension: ''
          - os: ubuntu-latest
            build_target: linux-arm64
            artifact_extension: ''

    runs-on: ${{ matrix.os }}  # For a list of available runner types, refer to
                               # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Publish
    - name: dotnet publish
      run: dotnet publish -c Release --self-contained -r ${{ matrix.build_target }} -o './publish/App_Data/Jobs/Triggered/${{ env.PROJECT_NAME }}-${{ matrix.build_target }}' ${{ env.PROJECT_ROOT }}
    
    # Rename artifact
    - name: Rename Output .exe
      shell: pwsh # Supported on all platforms
      run: Move-Item -Path './publish/App_Data/Jobs/Triggered/${{ env.PROJECT_NAME }}-${{ matrix.build_target }}/${{ env.PROJECT_NAME }}${{ matrix.artifact_extension }}' -Destination './publish/App_Data/Jobs/Triggered/${{ env.PROJECT_NAME }}-${{ matrix.build_target }}/${{ env.PROJECT_NAME }}_${{ matrix.build_target }}${{ matrix.artifact_extension }}'
    
    # Upload
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-${{ matrix.build_target }}
        path: |
          ./publish/App_Data/Jobs/Triggered/${{ env.PROJECT_NAME }}-${{ matrix.build_target }}/*
          !./publish/**/*.pdb
        overwrite: true
        if-no-files-found: 'error'
        retention-days: 1 # This is meant for me to download and set up a release, not long-term downloading
  